### PR TITLE
Add manhole.

### PR DESCRIPTION
**Pull request by dellis23**
👓 @spladug @ckwang8128 

Thoughts on this?  It runs fine locally and lets me inspect the garbage collector.  I think I'd need to package it since there isn't a package available for it already.  It has no other dependencies, which is nice.

### CODE REVIEW

**Comment by ckwang8128** [comment]
Not opposed, shouldn't be any performance impact right? getting something like this in for baseplate as a whole is worth thinking about, but I think having this set up for a test run to see its use cases is good.

**Comment by ckwang8128** [comment]
:nail_care: for the packaging

**Comment by spladug** [comment]
:nail_care: for packaging and I think we should get Jordan to review manhole. Also agree that if this works out here it'd be good to get it into `baseplate-serve` directly.

**Comment by dellis23** [comment]
Cool, I'll shoot a note to him.

**Review by JordanMilne — APPROVED** [review]
LGTM

**Pull request merged**
